# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfe95277742d9711074dbee8e528bbe62174440241632681c7dfd4a9460564d2e2218073c36b9c0419a0b41f15bc2c43df3334dd988b4734b5166aa2c1b5aa7c

test:
  secret_key_base: 9606c5ef072986c304c56c8d2062fe324119f931184cd0b195513b5b0ed20b554e2bcf1677f570ab448f52641ab251425933d310c04a8e3aab5448930a28a39a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
